### ISSUE TITLE
DTO kept in cache between suites

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-openapitools#19]
Hello,

I have 2 different suites using the same OAS but with different authorization token, and different data_mapping
It seems that the second suite does not properly reload the DTO_MAPPING and keeps data from the first one (as endpoints are the same)
I found a solution by calling `importlib.reload` to force the reload of the mapping, I did it on a commit on my personal fork https://github.com/Leemur89/robotframework-openapitools/commit/c81a9d1c52d691ca28561f2efd6b1d3d5cb416ed

Sorry I do not have time to raise a proper PR with tests as I'm going in vacations tomorrow but I did not want to lose track of that issue+solution so I did a quick 'n dirty commit on my fork and raised that issue.

I'll raise a proper PR with tests when I'm back

Regards,

**Comment by Leemur89** [comment]
Hello,
By distinct mapping name, do you mean a different mapping file with a different name? This is already what I am doing and unfortunately it does not fix the problem :(

**Comment by Leemur89** [comment]
Yes both mapping already have distinct names, in different data mapping python files
Let say I have a suite_a.robot file that uses data_mapping_A.py, and a suite_b.robot file that uses data_mapping_B.py
In data_mapping_A.py I have an attribute with value `foo`, and in data_mapping_B.py for the same endpoint, same attribute, a value `bar`, then when my full suite runs, I will have the value `foo` for both suite_a and suite_b (if suite_a is run first, and the opposite if suite_b runs first)

**Comment by Leemur89** [comment]
Actually it turns out I was importing the `DTO_MAPPING` from a parent mapping, and edited it:

```python
from parent import DTO_MAPPING

DTO_MAPPING = [("/myspecialendpoint", "post")] = MyDtoB
```

I simply copied it instead of reusing the same and I do not get the issue anymore:

```python
from parent import DTO_MAPPING

DTO_MAPPING = DTO_MAPPING.copy()
DTO_MAPPING = [("/myspecialendpoint", "post")] = MyDtoB
```

**Comment by robinmackaij** [comment]
Ah, the joys of mutability in Python. Glad you have it resolved!
